### ISSUE TITLE
task.py. AssertionError: No data from solver received. [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by vvvol** [ssmir/dcbc#2]
Take a look at the following jobs (shared for you):
https://everest.distcomp.org/jobs/59f760f1320000864a8b7649 (main job)
https://everest.distcomp.org/jobs/59f760f33200003d4c8b764d (children job, erroneous "id part" dd8_256, there are 128 subtasks).
When running DDNBN-application with 128 subtasks I see that some of running tasks become "FAILED" after various time intervals (from ~15 to ~100 and more minutes). I do not see any solvers' error neither in stderr, nor in stdout.
But in stderr of the FAILED tasks I see the following error stack trace (besides incumbents get/set messages):
[ErrorStackTrace.txt](https://github.com/distcomp/ddbnb/files/1428904/ErrorStackTrace.txt)

**Comment by ssmir** [comment]
The solver gets killed by the OOM killer. More memory is needed or you need tighter memory restrictions in the solver's config.
